# Generated by Django 4.2.1 on 2023-11-08 09:17

import APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=30)),
                ('studentRollNumber', models.CharField(max_length=30)),
                ('studentMail', models.CharField(max_length=30)),
                ('studentContact', models.CharField(max_length=30)),
                ('parentContact', models.CharField(max_length=30)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to=APP.models.getFileName)),
            ],
            options={
                'db_table': 'studentDetails',
            },
        ),
    ]
